services:
  cantaloupe:
    build: .
    ports:
      - "8182:8182"
    env_file:
      - .env
    volumes:
      - ${USERPROFILE}/Docker/scratch:/home/cantaloupe/images/
      - ${USERPROFILE}/.aws/credentials:/home/cantaloupe/.aws/credentials:ro
    #user: root  # required when running downloading KDU binaries (copies libs into /usr/lib)