services:
  cantaloupe:
    build: .
    ports:
      - "8182:8182"
    env_file:
      - .env
    volumes:
      - ${USERPROFILE}/Docker/scratch:/home/cantaloupe/images/
      - ${USERPROFILE}/.aws/credentials:/home/cantaloupe/.aws/credentials:ro
    # command: /opt/app/s3-config.sh
    # user: root  # required when running /opt/app/kakadu.sh (copies libs into /usr/lib)
    # command: /opt/app/kakadu.sh